{"dept":"EECS","class_no":["100"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/100.html","course_title":"Electrons, Photons, and Bits: Adventures in Electrical and Computer Engineering","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Allen Taflove"],"schedule":[{"days":"MTuWF","hours":"4-4:50"}]}}
{"dept":"EECS","class_no":["101"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/101.html","course_title":"An Intro to Computer Science for Everyone","fall_schedule":{"instructors":["Chris Riesbeck"],"schedule":[{"days":"MWF","hours":"11:00-11:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["110"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/110.html","course_title":"Intro to Computer Programming","fall_schedule":{"instructors":["Jack E. Tumblin"],"schedule":[{"days":"MWF","hours":"10-10:50"}],"comment":"C"},"winter_schedule":{"instructors":["Oliver S. Cossairt"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}],"comment":"Python"},"spring_schedule":{"instructors":["Aleksandar Kuzmanovic"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}],"comment":"Python"}}
{"dept":"EECS","class_no":["111"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/111.html","course_title":"Fundamentals of Computer Programming I","fall_schedule":{"instructors":["Ian Horswill"],"schedule":[{"days":"MWF","hours":"12:00-12:50"}]},"winter_schedule":{"instructors":["Sara Owsley Sood"],"schedule":[{"days":"MWF","hours":"12:00-12:50"}]},"spring_schedule":{"instructors":["Jesse Tov"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["120"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/120.html","course_title":"Intro to Computers & Info Technology","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["130"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/130.html","course_title":"Tools and Technology of the World Wide Web","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["202"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/202.html","course_title":"Intro to Electrical Engineering","fall_schedule":{"instructors":["Allen Taflove","Ilya Mikhelson","Hooman Mohseni"],"schedule":[{"days":"MTuWF","hours":"2-2:50"}]},"winter_schedule":{"instructors":["Allen Taflove","Ilya Mikhelson","Hooman Mohseni"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}]},"spring_schedule":{"instructors":["Allen Taflove","Ilya Mikhelson","Matthew Grayson"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}]}}
{"dept":"EECS","class_no":["203"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/203.html","course_title":"Intro to Computer Engineering","fall_schedule":{"instructors":["Russell Joseph"],"schedule":[{"days":"MTuWF","hours":"11-11:50"}]},"winter_schedule":{"instructors":["Chi-Haur Wu"],"schedule":[{"days":"MTuWF","hours":"11-11:50"}]},"spring_schedule":{"instructors":["Hai Zhou"],"schedule":[{"days":"MTuWF","hours":"11-11:50"}]}}
{"dept":"EECS","class_no":["205"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/205.html","course_title":"Fundamentals of Computer System Software","fall_schedule":{},"winter_schedule":{"instructors":["Russell Joseph"],"schedule":[{"days":"MTuWF","hours":"2-2:50"}]},"spring_schedule":{}}
{"dept":"COGSCI","class_no":["207"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/207-cogsci.html","course_title":"Introduction to Cognitive Modeling","fall_schedule":{"instructors":["Ken Forbus"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["211"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/211.html","course_title":"Fundamentals of Computer Programming II","fall_schedule":{"instructors":["Sara Owsley Sood"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{"instructors":["Jesse Tov"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"spring_schedule":{"instructors":["Sara Owsley Sood"],"schedule":[{"days":"MWF","hours":"2-2:50"}]}}
{"dept":"EECS","class_no":["212"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/212.html","course_title":"Mathematical Foundations of Computer Science","fall_schedule":{"instructors":["Aravindan Vijayaraghavan"],"schedule":[{"days":"MWF","hours":"3-3:50"}]},"winter_schedule":{"instructors":["Bennett"],"schedule":[{"days":"MWF","hours":"3-3:50"}]},"spring_schedule":{"instructors":["Bennett"],"schedule":[{"days":"MWF","hours":"3-3:50"}]}}
{"dept":"EECS","class_no":["213"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/213.html","course_title":"Intro to Computer Systems","fall_schedule":{"instructors":["Nikos Hardavellas"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"winter_schedule":{"instructors":["St-Amour"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"spring_schedule":{"instructors":["St-Amour"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["214"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/214.html","course_title":"Data Structures and Data Management","fall_schedule":{"instructors":["Jesse Tov"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Ian Horswill"],"schedule":[{"days":"MWF","hours":"1-1:50"}]}}
{"dept":"EECS","class_no":["221"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/221.html","course_title":"Fundamentals of Circuits","fall_schedule":{},"winter_schedule":{"instructors":["Martin Plonus"],"schedule":[{"days":"MTuWF","hours":"9-9:50"}]},"spring_schedule":{"instructors":["Prem Kumar"],"schedule":[{"days":"MTuWF","hours":"2-2:50"}]}}
{"dept":"EECS","class_no":["222"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/222.html","course_title":"Fundamentals of Signals and Systems ","fall_schedule":{"instructors":["Thrasyvoulos N. Pappas"],"schedule":[{"days":"MTuWF","hours":"2-3"}]},"winter_schedule":{"instructors":["Maglaveras"],"schedule":[{"days":"MTuWF","hours":"2-2:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["223"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/223.html","course_title":"Fundamentals of Solid State Engineering","fall_schedule":{"instructors":["Pedram Khalili"],"schedule":[{"days":"MTuWF","hours":"9-9:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Koray Aydin"],"schedule":[{"days":"MTuWF","hours":"9-9:50"}]}}
{"dept":"EECS","class_no":["224"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/224.html","course_title":"Fundamentals of Electromagnetics and Photonics","fall_schedule":{"instructors":["Allen Taflove"],"schedule":[{"days":"MTuWF","hours":"11-11:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Allen Taflove"],"schedule":[{"days":"MTuWF","hours":"1-1:50"}]}}
{"dept":"EECS","class_no":["225"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/225.html","course_title":"Fundamentals of Electronics","fall_schedule":{"instructors":["C.H. Wu"],"schedule":[{"days":"MTuWF","hours":"1-1:50"}]},"winter_schedule":{"instructors":["C.H. Wu"],"schedule":[{"days":"MTuWF","hours":"3-3:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["230"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/230.html","course_title":"Programming for Engineers","fall_schedule":{},"winter_schedule":{"instructors":["Jesse Tov"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["250"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/250.html","course_title":"Physical Electronics and Devices","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["295"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/295-1.html","course_title":"Intensive Program Design","fall_schedule":{"instructors":["Jesse Tov","Robby Findler"],"schedule":[{"days":"TuTh","hours":"12-2:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["295"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/295-2.html","course_title":"Fundamentals of Computer Programming 1.5","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Sara Owsley Sood"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["301"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/301.html","course_title":"Introduction to Robotics Laboratory","fall_schedule":{"instructors":["Brenna Argall"],"schedule":[{"days":"TuTh","hours":"2:00-6:00"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["302"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/302.html","course_title":"Probabilistic Systems","fall_schedule":{"instructors":["Ermin Wei"],"schedule":[{"days":"MTuWF","hours":"9-9:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Dongning Guo"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}]}}
{"dept":"EECS","class_no":["303"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/303.html","course_title":"Advanced Digital Logic Design","fall_schedule":{"instructors":["Seda O. Memik"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Jie Gu"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["307"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/307.html","course_title":"Communications Systems","fall_schedule":{"instructors":["Michael Honig"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["308"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/308.html","course_title":"Applied Electromagnetics and Photonics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["313","413"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/313-413.html","course_title":"Tangible Interaction Design and Learning","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Michael Horn"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["314"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/314.html","course_title":"Technology & Human Interaction","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Gergle"],"schedule":[{"days":"MW","hours":"9:30-10:50"}]}}
{"dept":"EECS","class_no":["315","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/315.html","course_title":"Design, Technology, and Research ","fall_schedule":{"instructors":["Haoqi Zhang"],"schedule":[{"days":"M","hours":"W"}]},"winter_schedule":{"instructors":["Haoqi Zhang"],"schedule":[{"days":"F","hours":"2-5"}]},"spring_schedule":{"instructors":["Haoqi Zhang"],"schedule":[{"days":"F","hours":"2-5"}]}}
{"dept":"EECS","class_no":["317"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/317.html","course_title":"Data Management and Information Processing","fall_schedule":{"instructors":["Tarzia"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Nikos Hardavellas"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["321"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/321.html","course_title":"Programming Languages","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["St-Amour"],"schedule":[{"days":"TuTh","hours":"11:00-12:20"}]}}
{"dept":"EECS","class_no":["322"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/322.html","course_title":"Compiler Construction","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Simone Campanoni"],"schedule":[{"days":"MW","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["325"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/325.html","course_title":"Artificial Intelligence Programming","fall_schedule":{"instructors":["Chris Riesbeck"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"BME","class_no":["325"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/325-bme.html","course_title":"Introduction to Medical Imaging","fall_schedule":{"instructors":["Alan V. Sahakian"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["328"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/328.html","course_title":"Numerical Methods for Engineers ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["330"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/330.html","course_title":"Human Computer Interaction","fall_schedule":{"instructors":["Michael Horn"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"winter_schedule":{"instructors":["Eleanor O'Rourke"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"spring_schedule":{"instructors":["Beheshti"],"schedule":[{"days":"MWF","hours":"1-1:50"}]}}
{"dept":"EECS","class_no":["331"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/331.html","course_title":"Introduction to Computational Photography","fall_schedule":{"instructors":["Oliver S. Cossairt"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["332"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/332.html","course_title":"Introduction to Computer Vision","fall_schedule":{"instructors":["Chi-Haur Wu","Ying Wu"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["333"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/333.html","course_title":"Intro to Communication Networks","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Dongning Guo"],"schedule":[{"days":"MWF","hours":"11-11:50"}]}}
{"dept":"EECS","class_no":["335"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/335.html","course_title":"Intro to the Theory of Computation","fall_schedule":{},"winter_schedule":{"instructors":["Anindya De"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["336"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/336.html","course_title":"Design & Analysis of Algorithms","fall_schedule":{"instructors":["Jason D. Hartline"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{"instructors":["Konstantin Makarychev"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"spring_schedule":{"instructors":["Konstantin Makarychev"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["337"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/337.html","course_title":"Natural Language Processing","fall_schedule":{},"winter_schedule":{"instructors":["Larry Birnbaum"],"schedule":[{"days":"MW","hours":"11-12:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["338"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/338.html","course_title":"Practicum in Intelligent Information Systems","fall_schedule":{"instructors":["Larry Birnbaum","Kristian J. Hammond"],"schedule":[{"days":"M","hours":"6-9"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Larry Birnbaum"],"schedule":[{"days":"M","hours":"6-9"}]}}
{"dept":"EECS","class_no":["339"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/339.html","course_title":"Intro to Databases","fall_schedule":{"instructors":["Jennie M. Rogers"],"schedule":[{"days":"MWF","hours":"4-4:50"}]},"winter_schedule":{"instructors":["Jennie M. Rogers"],"schedule":[{"days":"MWF","hours":"4-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["340"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/340.html","course_title":"Introduction to Computer Networking","fall_schedule":{},"winter_schedule":{"instructors":["Aleksandar Kuzmanovic"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"spring_schedule":{"instructors":["Tarzia"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["343"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/343.html","course_title":"Operating Systems","fall_schedule":{"instructors":["Fabian E. Bustamante"],"schedule":[{"days":"MW","hours":"8-9:20"}]},"winter_schedule":{"instructors":["Tarzia"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["344"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/344.html","course_title":"Design of Problem Solvers","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["345"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/345.html","course_title":"Distributed Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Fabian E. Bustamante"],"schedule":[{"days":"MW","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["346"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/346.html","course_title":"Microprocessor System Design","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Josiah Hester"],"schedule":[{"days":"MTuWF","hours":"10-10:50"}]}}
{"dept":"EECS","class_no":["347"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/347-1.html","course_title":"Microprocessor Systems Project I","fall_schedule":{},"winter_schedule":{"instructors":["Larry Henschen"],"schedule":[{"days":"MWF","hours":"9-9:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["347-2"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/347-2.html","course_title":"Microprocessor Systems Project II","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Larry Henschen"],"schedule":[{"days":"MWF","hours":"9-9:50"}]}}
{"dept":"EECS","class_no":["348"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/348.html","course_title":"Intro to Artificial Intelligence","fall_schedule":{"instructors":["Kristian J. Hammond"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{"instructors":["Wilson"],"schedule":[{"days":"MWF","hours":"3-3:50"}]},"spring_schedule":{"instructors":["Michael Rubenstein"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["349"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/349.html","course_title":"Machine Learning","fall_schedule":{"instructors":["Bryan Pardo"],"schedule":[{"days":"MW","hours":"3-4:20"},{"days":"F","hours":"3-3:50"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Douglas Downey"],"schedule":[{"days":"MWF","hours":"1-1:50"}]}}
{"dept":"EECS","class_no":["350"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/350.html","course_title":"Introduction to Computer Security","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["351-1"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/351-1.html","course_title":"Intro to Computer Graphics","fall_schedule":{},"winter_schedule":{"instructors":["Jack E. Tumblin"],"schedule":[{"days":"MWF","hours":"10-10:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["351-2"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/351-2.html","course_title":"Intermediate Computer Graphics ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Jack E. Tumblin"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]}}
{"dept":"EECS","class_no":["352"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/352.html","course_title":"Machine Perception of Music & Audio","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["354"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/354.html","course_title":"Network Penetration and Security","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["355"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/355.html","course_title":"Asic and FPGA Design","fall_schedule":{"instructors":["Zaretsky"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["356"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/356.html","course_title":"Introduction to Formal Verification","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["357"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/357.html","course_title":"Introduction to VLSI CAD","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["358"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/358.html","course_title":"Intro to Parallel Computing","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Gokhan Memik"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["359"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/359.html","course_title":"Digital Signal Processing","fall_schedule":{"instructors":["Thrasyvoulos N. Pappas"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["360"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/360.html","course_title":"Introduction to Feedback Systems","fall_schedule":{},"winter_schedule":{"instructors":["Randy Freeman"],"schedule":[{"days":"MWF","hours":"10-10:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["361"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/361.html","course_title":"Computer Architecture I ","fall_schedule":{"instructors":["Gokhan Memik"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["362"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/362.html","course_title":"Computer Architecture Project","fall_schedule":{},"winter_schedule":{"instructors":["Yan","Beigi"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["363"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/363.html","course_title":"Digital Filtering","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["366","466"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/366-466.html","course_title":"Embedded Systems ","fall_schedule":{},"winter_schedule":{"instructors":["Larry Henschen"],"schedule":[{"days":"MWF","hours":"11-12"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["368","468"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/368-468.html","course_title":"Programming Massively Parallel Processors with CUDA","fall_schedule":{},"winter_schedule":{"instructors":["Nikos Hardavellas"],"schedule":[{"days":"TuTh","hours":"2:00-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["370"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/370.html","course_title":"Computer Game Design","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["371"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/371.html","course_title":"Knowledge Representation and Reasoning","fall_schedule":{},"winter_schedule":{"instructors":["Ken Forbus"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["372","472"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/372-472.html","course_title":"Designing and Constructing Models with Multi-Agent Languages","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Uri Wilensky"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["374"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/374.html","course_title":"Intro to Digital Control","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Randy Freeman"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["378"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/378.html","course_title":"Digital Communications","fall_schedule":{},"winter_schedule":{"instructors":["C.C. Lee"],"schedule":[{"days":"MWF","hours":"11-11:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["379"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/379.html","course_title":"Lasers and Coherent Optics","fall_schedule":{"instructors":["Seng-Tiong Ho"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["380"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/380.html","course_title":"Wireless Communications","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Michael Honig"],"schedule":[{"days":"MW","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["381"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/381.html","course_title":"Electronic Properties of Materials","fall_schedule":{"instructors":["Hooman Mohseni"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["382"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/382.html","course_title":"Photonic Information Processing","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Seng-Tiong Ho"],"schedule":[{"days":"MW","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["383"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/383.html","course_title":"Fiber-Optic Communications","fall_schedule":{},"winter_schedule":{"instructors":["Horace Yuen"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["384"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/384.html","course_title":"Solid State Electronic Devices","fall_schedule":{"instructors":["Matthew Grayson"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["385"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/385.html","course_title":"Optoelectronics","fall_schedule":{},"winter_schedule":{"instructors":["Koray Aydin"],"schedule":[{"days":"MW","hours":"2-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["386"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/386.html","course_title":"Computational Electromagnetics and Photonics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["388"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/388.html","course_title":"Nanotechnology","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Manijeh Razeghi"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]}}
{"dept":"EECS","class_no":["389"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/389.html","course_title":"Superconductivity and its Applications","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["390"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/390.html","course_title":"Intro to Robotics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["C-H Wu"],"schedule":[{"days":"MWF","hours":"1-1:50"}]}}
{"dept":"EECS","class_no":["391"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/391.html","course_title":"CMOS VLSI Circuits Design","fall_schedule":{},"winter_schedule":{"instructors":["Jie Gu"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["392"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/392.html","course_title":"VLSI Systems Design Projects","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Zaretsky"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["393","493"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/393-493.html","course_title":"Design and Analysis of High-Speed Integrated Circuits","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["394"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/394.html","course_title":"Software Project Management & Development","fall_schedule":{"instructors":["Chris Riesbeck"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]},"winter_schedule":{},"spring_schedule":{"instructors":["Chris Riesbeck"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["395"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-1.html","course_title":"Economics and Computation","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-2.html","course_title":"Probabilistic Systems","fall_schedule":{"instructors":["Ermin Wei"],"schedule":[{"days":"MTuWF","hours":"9-9:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395-20"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-20-dsgn.html","course_title":"Data as Art","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-3.html","course_title":"Quantum Computation","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Horace Yuen"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-10.html","course_title":"Algorithmic Mechanism Design ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-11.html","course_title":"Algorithmic Techniques for Bioinformatics Seminar","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-13.html","course_title":"Cognitive Simulation for Virtual Characters ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-14.html","course_title":"Biometrics","fall_schedule":{"instructors":["X. Chen"],"schedule":[{"days":"Tu","hours":"6-9"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-15.html","course_title":"Building Next-Generation AI Applications with IBM Watson","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-16.html","course_title":"Cardiovascular Instrumentation ","fall_schedule":{},"winter_schedule":{"instructors":["Alan V. Sahakian"],"schedule":[{"days":"MWF","hours":"1-1:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-18.html","course_title":"Collaboration Technology ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-20.html","course_title":"Computational Auditory Scene Analysis","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-21.html","course_title":"Engineering System Design I","fall_schedule":{},"winter_schedule":{"instructors":["Ilya Mikhelson"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-22.html","course_title":"Engineering System Design II","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Ilya Mikhelson"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-23.html","course_title":"Introduction to Smart Grid Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Ermin Wei"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-24.html","course_title":"A Hands-on Course in Communication Systems ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-26.html","course_title":"Human-level Artificial Intelligence ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-3.html","course_title":"Advanced Compiler Hacking","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-30.html","course_title":"Metamaterials and Plasmonics, and their Applications","fall_schedule":{"instructors":["Koray Aydin"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-31.html","course_title":"Mixed Signal Circuits Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-32.html","course_title":"Mobile Apps and Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-33.html","course_title":"Object-Oriented Languages and Environments ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-34.html","course_title":"The Probabilistic Method","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-35.html","course_title":"Machine Learning: Foundations, Applications, and Algorithms","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Aggelos K. Katsaggelos"],"schedule":[{"days":"MWF","hours":"10-10:50"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-36.html","course_title":"Advanced Quantum Transport & Magneto Transport","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-37.html","course_title":"Deep Reinforcement Learning from Scratch","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Borhani","Watt"],"schedule":[{"days":"W","hours":"5-8"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-38.html","course_title":"Web Information Retrieval and Extraction","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-39.html","course_title":"Geospatial Vision and Visualization ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Yan Chen"],"schedule":[{"days":"M","hours":"6-9"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-4.html","course_title":"Advanced Digital System Design with FPGAS","fall_schedule":{},"winter_schedule":{"instructors":["Zaretsky"],"schedule":[{"days":"MW","hours":"3:30-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-40.html","course_title":"Technology Infrastructure: Concepts, Requirements, Design and Operation ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-41.html","course_title":"Introduction to Computational Learning Theory","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-42.html","course_title":"Internet-of-Things Sensors, Systems, and Applications","fall_schedule":{},"winter_schedule":{"instructors":["Josiah Hester"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-44.html","course_title":"Optimization Techniques for Machine Learning and Deep Learning","fall_schedule":{"instructors":["Borhani","Watt"],"schedule":[{"days":"MW","hours":"9:30-11"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-45.html","course_title":"Deep Learning Foundations from Scratch","fall_schedule":{"instructors":["Borhani","Watt"],"schedule":[{"days":"MWF","hours":"2-2:50"}]},"winter_schedule":{"instructors":["Borhani","Watt"],"schedule":[{"days":"W","hours":"5-8"}]},"spring_schedule":{"instructors":["Watt"],"schedule":[{"days":"M","hours":"5-8"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-46.html","course_title":"Bioelectric Systems Modeling & Analysis","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Maglaveras"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-47.html","course_title":"Personal Health Systems","fall_schedule":{"instructors":["Maglaveras"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-48.html","course_title":"Modeling and Synthesis of Cyber-Physical Systems","fall_schedule":{},"winter_schedule":{"instructors":["Qi Zhu"],"schedule":[{"days":"MW","hours":"2-3:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-5.html","course_title":"Advanced Low Power Digital and Mixed-signal Integrated Circuit Design","fall_schedule":{"instructors":["Gu"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-6.html","course_title":"Advanced Topics in Computer Architecture ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Nikos Hardavellas"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-7.html","course_title":"The Art of Multicore Concurrent Programming ","fall_schedule":{},"winter_schedule":{"instructors":["Hai Zhou"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-8.html","course_title":"Algorithmic DNA Self-Assembly Seminar (Kao) ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["395","495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/395-495-9.html","course_title":"Algorithmic and Economic Aspects of Social Networks","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396.html","course_title":"Game Design and Development","fall_schedule":{"instructors":["Horswill"],"schedule":[{"days":"MWF","hours":"3-3:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496.html","course_title":"Special Topics in Game AI - Logic Programming","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Ian Horswill"],"schedule":[{"days":"MWF","hours":"4-4:50"}]}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-1.html","course_title":"Companion Cognitive System Studio","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Ken Forbus"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-10.html","course_title":"Programming Languages Seminar ","fall_schedule":{},"winter_schedule":{"instructors":["Christos Dimoulas"],"schedule":[{"days":"W","hours":"10:30-12"},{"days":"W","hours":"3:30-5"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-11.html","course_title":"Randomized Algorithms","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Anindya De"],"schedule":[{"days":"M","hours":"10-12:50"}]}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-12.html","course_title":"Affective Computing Seminar","fall_schedule":{"instructors":["Wilson"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-13.html","course_title":"Type Systems","fall_schedule":{},"winter_schedule":{"instructors":["Jesse Tov","Robby Findler"],"schedule":[{"days":"TuTh","hours":"11-12:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-14.html","course_title":"Multi-Modal Analytics","fall_schedule":{},"winter_schedule":{"instructors":["Marcelo Worsley"],"schedule":[{"days":"F","hours":"9-12"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-2.html","course_title":"Code Analysis and Transformation","fall_schedule":{"instructors":["Simone Campanoni"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-5.html","course_title":"Computational Geometry ","fall_schedule":{"instructors":["Bennett"],"schedule":[{"days":"MW","hours":"4-5:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-6.html","course_title":"Data Science Seminar","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Jennie M. Rogers"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-7.html","course_title":"Special Topics in Swarms and Multi-robot Systems","fall_schedule":{"instructors":["Michael Rubenstein"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-8.html","course_title":"Quadrotor Design and Control","fall_schedule":{},"winter_schedule":{"instructors":["Michael Rubenstein"],"schedule":[{"days":"Th","hours":"1-4"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["396","496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/396-496-9.html","course_title":"Systems Programming in Rust","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Jesse Tov"],"schedule":[{"days":"TuTh","hours":"12:30-1:50"}]}}
{"dept":"EECS","class_no":["397"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397.html","course_title":"Digital Luthier","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Bryan Pardo"],"schedule":[{"days":"M","hours":"2:30-5:30"}]}}
{"dept":"EECS","class_no":["397"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-1.html","course_title":"Software Construction","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Robby Findler","Christos Dimoulas"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497.html","course_title":"Computational Photography Seminar ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Oliver S. Cossairt"],"schedule":[{"days":"M","hours":"3-6"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-1.html","course_title":"Game Development Studio ","fall_schedule":{},"winter_schedule":{"instructors":["Zubek"],"schedule":[{"days":"MW","hours":"6-7:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-11.html","course_title":"Internet-scale Experimentation","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-13.html","course_title":"Spatial Data Science and Spatial Computing","fall_schedule":{"instructors":["Hecht"],"schedule":[{"days":"WF","hours":"1-2:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-14.html","course_title":"Wireless and Mobile  Health (mHealth)","fall_schedule":{},"winter_schedule":{"instructors":["Alshurafa"],"schedule":[{"days":"TuTh","hours":"5-6:30"}]},"spring_schedule":{}}
{"dept":"","class_no":["397"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-15.html","course_title":"Innovation Lab: Building Technologies for the Law","fall_schedule":{},"winter_schedule":{"instructors":["Kristian J. Hammond"],"schedule":[{"days":"Tu","hours":"2:30-5:30"}]},"spring_schedule":{"instructors":["Kristian J. Hammond"],"schedule":[{"days":"Tu","hours":"2:30-5:30"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-16.html","course_title":"Advanced Multimodal Interfaces and Analytics Research","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Marcelo Worsley"],"schedule":[{"days":"TBA"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-2.html","course_title":"Advanced Topics in Compilers","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Simone Campanoni"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-3.html","course_title":"Digital Forensics and Incident Response","fall_schedule":{},"winter_schedule":{"instructors":["Yan Chen"],"schedule":[{"days":"MW","hours":"11-12:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-4.html","course_title":"(Special Topics) Innovation in Journalism & Technology","fall_schedule":{},"winter_schedule":{"instructors":["Kristian J. Hammond"],"schedule":[{"days":"TuTh","hours":"9:30-11:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-6.html","course_title":"Internet of Things Networks Seminar","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Aleksandar Kuzmanovic"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-8.html","course_title":"Social Computing and Crowd Sourcing","fall_schedule":{"instructors":["Haoqi Zhang"],"schedule":[{"days":"TBA"}]},"winter_schedule":{"instructors":["Haoqi Zhang"],"schedule":[{"days":"TBA"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["397","497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/397-497-9.html","course_title":"Inclusive Making","fall_schedule":{"instructors":["Marcelo Worsley"],"schedule":[{"days":"F","hours":"9-12"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["398"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/398.html","course_title":"Electrical Engineering Design","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["401"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/401.html","course_title":"Fundamentals of Electronic Devices","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["402"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/402.html","course_title":"Advanced Electronic Devices","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Hooman Mohseni"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["403"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/403.html","course_title":"Quantum Semiconductors","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Matthew Grayson"],"schedule":[{"days":"TuTh","hours":"11-12:20"}]}}
{"dept":"EECS","class_no":["404"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/404.html","course_title":"Quantum Electronics","fall_schedule":{"instructors":["Selim Shahriar"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["405"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/405.html","course_title":"Advanced Photonics","fall_schedule":{},"winter_schedule":{"instructors":["Hooman Mohseni"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["406"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/406.html","course_title":"Nonlinear Optics","fall_schedule":{"instructors":["Prem Kumar"],"schedule":[{"days":"MW","hours":"2-3:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["407"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/407.html","course_title":"Quantum Optics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["409"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/409.html","course_title":"Semiconductor Lasers","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["410"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/410.html","course_title":"System Theory","fall_schedule":{"instructors":["Arthur Butz"],"schedule":[{"days":"MWF","hours":"11-11:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["411"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/411.html","course_title":"Fundamentals and Applications of Special Relativity","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Selim Shahriar"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["414"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/414.html","course_title":"Advanced Topics in Quantum Electronics","fall_schedule":{},"winter_schedule":{"instructors":["Selim Shahriar"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["418"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/418.html","course_title":"Advanced Digital Signal Processing","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["420"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/420.html","course_title":"Digital Image Processing","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Aggelos K. Katsaggelos"],"schedule":[{"days":"Th","hours":"5-8"}]}}
{"dept":"EECS","class_no":["421"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/421.html","course_title":"Multimedia Signal Processing","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["422"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/422.html","course_title":"Random Processes in Communications and Control I","fall_schedule":{},"winter_schedule":{"instructors":["Randall Berry"],"schedule":[{"days":"MW","hours":"3:30-5:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["423"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/423.html","course_title":"Random Processes in Communications and Control II","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["424"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/424.html","course_title":"Distributed Optimization","fall_schedule":{},"winter_schedule":{"instructors":["Ermin Wei"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["425"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/425.html","course_title":"Quantum Electronics II: Noise, Modulation, and Quantum Properties of Laser Emissions ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["426"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/426.html","course_title":"Signal Detection and Estimation","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["427"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/427.html","course_title":"Optical Communications","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["428"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/428.html","course_title":"Information Theory","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["429"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/429.html","course_title":"Selected Topics in Quantum Information Science and Technology","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["430"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/430.html","course_title":"Design of Interactive Learning Environments","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["431"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/431.html","course_title":"Human Perception and Electronic Media","fall_schedule":{},"winter_schedule":{"instructors":["Thrasyvoulos N. Pappas"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["432"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/432.html","course_title":"Advanced Computer Vision","fall_schedule":{},"winter_schedule":{"instructors":["Chi-Haur Wu","Ying Wu"],"schedule":[{"days":"TuTh","hours":"11:00-12:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["433"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/433.html","course_title":"Statistical Pattern Recognition","fall_schedule":{},"winter_schedule":{"instructors":["Chi-Haur Wu","Ying Wu"],"schedule":[{"days":"TuTh","hours":"2:00-3:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["435"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/435.html","course_title":"Neural Networks","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["438"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/438.html","course_title":"Interdisciplinary Nonlinear Dynamics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["440"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/440.html","course_title":"Advanced Networking","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["441"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/441.html","course_title":"Resource Virtualization","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["442"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/442.html","course_title":"Dynamic Behavior of Applications, Hosts, and Networks","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["443"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/443.html","course_title":"Advanced Operating Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["446"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/446.html","course_title":"Kernel and Other Low-level Software Development","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Peter Dinda"],"schedule":[{"days":"TuTh","hours":"9:30-10:50"}]}}
{"dept":"EECS","class_no":["450"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/450.html","course_title":"Internet Security","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["452"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/452.html","course_title":"Advanced Computer Architecture I","fall_schedule":{},"winter_schedule":{"instructors":["Gokhan Memik"],"schedule":[{"days":"MW","hours":"12:30-1:50"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["453"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/453.html","course_title":"Parallel Architectures","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Russell Joseph"],"schedule":[{"days":"MW","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["454"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/454.html","course_title":"Advanced Communication Networks","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["455"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/455.html","course_title":"Distributed Computing Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["457"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/457.html","course_title":"Advanced Algorithms","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["458"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/458.html","course_title":"Parallel Algorithms for VLSI Computer-Aided Design","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["459"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/459.html","course_title":"VLSI Algorithmics","fall_schedule":{},"winter_schedule":{"instructors":["Seda O. Memik"],"schedule":[{"days":"MW","hours":"2-3:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["463"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/463.html","course_title":"Adaptive Filters","fall_schedule":{},"winter_schedule":{"instructors":["Michael Honig"],"schedule":[{"days":"MW","hours":"2-3:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["469"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/469.html","course_title":"Machine Learning and Artificial Intelligence for Robotics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["472"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/472.html","course_title":"Designing and Constructing Models with Multi-Agent Languages","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Uri Wilensky"],"schedule":[{"days":"TuTh","hours":"2-3:20"}]}}
{"dept":"EECS","class_no":["473-1"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/473-1.html","course_title":"NUvention: Web + Media (ENTREP 473)","fall_schedule":{},"winter_schedule":{"instructors":["Marasco","Warren","Gordon"],"schedule":[{"days":"Tu","hours":"2-5"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["473-2"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/473-2.html","course_title":"NUvention: Web + Media (ENTREP 473)","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Marasco","Warren","Gordon"],"schedule":[{"days":"Tu","hours":"2-5"}]}}
{"dept":"EECS","class_no":["474"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/474.html","course_title":"Probabilistic Graphical Models","fall_schedule":{"instructors":["Douglas Downey"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["478"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/478.html","course_title":"Advanced Digital Communications","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["479"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/479.html","course_title":"Nonlinear Optimization","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495.html","course_title":"Machine Learning and Artificial Intelligence for Robotics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-1.html","course_title":"Intensive Program Design","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-10.html","course_title":"Introduction to Database Systems","fall_schedule":{"instructors":["Peter Scheuermann"],"schedule":[{"days":"MW","hours":"11-12:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"ENTREP","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-14-entrep.html","course_title":"NUvention Impact ","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Werwath"],"schedule":[{"days":"Tu","hours":"6:30-9:30"}]}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-18.html","course_title":"Game Theory and Networked Systems","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-19.html","course_title":"Introduction to Computational Linguistics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-2.html","course_title":"Introduction to Nanophotonics and Plasmonics Science and Technology","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Seng-Tiong Ho"],"schedule":[{"days":"MW","hours":"8-9:30"}]}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-3.html","course_title":"Introduction to Nonlinear Control Theory","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-4.html","course_title":"Advanced Quantum Transport & Magneto Transport","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-5.html","course_title":"Robot Design Studio","fall_schedule":{},"winter_schedule":{"instructors":["Worth","Lynch"],"schedule":[{"days":"WF","hours":"12-1:20"}]},"spring_schedule":{"instructors":["Worth","Lynch"],"schedule":[{"days":"WF","hours":"12-1:20"}]}}
{"dept":"EECS","class_no":["495"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/495-7.html","course_title":"Statistical Optics","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Horace Yuen"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496.html","course_title":"Computational Complexity ","fall_schedule":{"instructors":["Anindya De"],"schedule":[{"days":"F","hours":"1-3:50"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-1.html","course_title":"Topics in Theoretical Machine Learning","fall_schedule":{},"winter_schedule":{"instructors":["Aravindan Vijayaraghavan"],"schedule":[{"days":"F","hours":"1-4"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-2.html","course_title":"Graduate Algorithms","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Aravindan Vijayaraghavan"],"schedule":[{"days":"TuTh","hours":"3:30-4:50"}]}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-4.html","course_title":"Seminar in Statistical Language Modeling ","fall_schedule":{},"winter_schedule":{"instructors":["Douglas Downey"],"schedule":[{"days":"Tu","hours":"1-3:30"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-5.html","course_title":"Distributed Systems in Challenging Environments","fall_schedule":{},"winter_schedule":{"instructors":["Fabian E. Bustamante"],"schedule":[{"days":"MW","hours":"11-12:20"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-6.html","course_title":"Computational Auditory Scene Analysis","fall_schedule":{},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["496"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/496-7.html","course_title":"The Design of Technological Tools for Thinking and Learning","fall_schedule":{},"winter_schedule":{"instructors":["Uri Wilensky"],"schedule":[{"days":"W","hours":"2-5"}]},"spring_schedule":{}}
{"dept":"EECS","class_no":["497"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/497.html","course_title":"Peer Grading","fall_schedule":{"instructors":["Jason D. Hartline"],"schedule":[{"days":"Tu","hours":"1-3:20"}]},"winter_schedule":{},"spring_schedule":{}}
{"dept":"EECS","class_no":["510"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/510.html","course_title":"Social Media Mining","fall_schedule":{},"winter_schedule":{},"spring_schedule":{"instructors":["Alok Choudhary"],"schedule":[{"days":"F","hours":"2-4:50"}]}}
{"dept":"EECS","class_no":["512"],"course_description_link":"https://www.mccormick.northwestern.edu/eecs/courses/previous-descriptions/512.html","course_title":"Parallelism Seminar","fall_schedule":{},"winter_schedule":{"instructors":["Peter Dinda","Simone Campanoni","Nikos Hardavellas"],"schedule":[{"days":"F","hours":"10-1"}]},"spring_schedule":{}}